site_name: Jeffrey Knowledge Base
theme:
  name: material
  features:
    - navigation.tabs # Adds top-level directories (API Test, Web Test) to a top bar
    - navigation.sections # Groups your sidebar items clearly into visible sections
    - navigation.expand # Forces the sidebar folders to stay expanded by default
  palette: # (1)!
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 # (2)!
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple

plugins:
  - search
  - tags

search:
  exclude: true
