name: Deploy MkDocs Blog

on:
  push:
    branches:
      - main # or master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 2. Install MkDocs and the Material Theme
      - name: Install Dependencies
        run: |
          pip install mkdocs-material

      # 3. Build the static site and deploy it straight to GitHub Pages
      - name: Build and Deploy to GitHub Pages
        run: |
          # The --force flag ensures it overwrites old deployment caches smoothly
          mkdocs gh-deploy --force
